import os
import re
import json
import arxiv
import yaml
import logging
import argparse
import datetime
import requests

logging.basicConfig(format='[%(asctime)s %(levelname)s] %(message)s',
                    datefmt='%m/%d/%Y %H:%M:%S',
                    level=logging.INFO)

github_url = "https://api.github.com/search/repositories"
arxiv_url = "http://arxiv.org/"

def load_config(config_file:str) -> dict:
    '''
    config_file: input config file path
    return: a dict of configuration
    '''
    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        def parse_filters(filters:list, field='all'):
            # arXiv's query grammar requires spaces around boolean operators.
            # The field can be ``ti`` (title) for a precise topical feed or
            # ``all`` when abstract matches are useful too.
            terms = []
            for filter_word in filters:
                if len(filter_word.split()) > 1:
                    terms.append(f'{field}:"{filter_word}"')
                else:
                    terms.append(f'{field}:{filter_word}')
            return "(" + " OR ".join(terms) + ")"
        for k, v in config['keywords'].items():
            query = parse_filters(v['filters'], v.get('field', 'all'))
            categories = v.get('categories', [])
            if categories:
                category_query = " OR ".join(f'cat:{category}' for category in categories)
                query = f"{query} AND ({category_query})"
            keywords[k] = query
        return keywords
    with open(config_file,'r') as f:
        config = yaml.load(f,Loader=yaml.FullLoader) 
        config['kv'] = pretty_filters(**config)
        logging.info(f'config = {config}')
    return config 

def get_authors(authors, first_author = False):
    output = str()
    if first_author == False:
        output = ", ".join(str(author) for author in authors)
    else:
        output = authors[0]
    return output
def sort_papers(papers):
    """Sort rows by their displayed update date, newest first."""
    def sort_key(item):
        row = str(item[1])
        match = re.search(r"\|\**(\d{4}-\d{2}-\d{2})\**\|", row)
        return match.group(1) if match else "0000-00-00"

    return dict(sorted(papers.items(), key=sort_key, reverse=True))
def load_json_file(filename):
    """Load a JSON data file, treating a missing/empty file as an empty object."""
    parent = os.path.dirname(filename)
    if parent:
        os.makedirs(parent, exist_ok=True)
    if not os.path.exists(filename):
        return {}
    with open(filename, "r") as f:
        content = f.read().strip()
    return json.loads(content) if content else {}


def get_code_link(qword:str) -> str:
    """
    This short function was auto-generated by ChatGPT. 
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    try:
        # query = f"arxiv:{arxiv_id}"
        query = f"{qword}"
        params = {
            "q": query,
            "sort": "stars",
            "order": "desc"
        }
        r = requests.get(github_url, params=params, timeout=20)
        r.raise_for_status()
        results = r.json()
        code_link = None
        if "total_count" in results and results["total_count"] > 0:
            code_link = results["items"][0]["html_url"]
        return code_link
    except Exception as e:
        logging.debug(f"GitHub search failed for {qword}: {e}")
        return None
  
def get_daily_papers(topic,query="slam", max_results=2):
    """
    @param topic: str
    @param query: str
    @return paper_with_code: dict
    """
    # output 
    content = dict() 
    content_to_web = dict()
    client = arxiv.Client()
    search = arxiv.Search(
        query = query,
        max_results = max_results,
        sort_by = arxiv.SortCriterion.SubmittedDate
    )

    for result in client.results(search):

        paper_id            = result.get_short_id()
        paper_title         = result.title
        paper_url           = result.entry_id
        paper_abstract      = result.summary.replace("\n"," ")
        paper_authors       = get_authors(result.authors)
        paper_first_author  = get_authors(result.authors,first_author = True)
        primary_category    = result.primary_category
        publish_time        = result.published.date()
        update_time         = result.updated.date()
        comments            = result.comment

        logging.info(f"Time = {update_time} title = {paper_title} author = {paper_first_author}")

        # eg: 2108.09112v1 -> 2108.09112
        ver_pos = paper_id.find('v')
        if ver_pos == -1:
            paper_key = paper_id
        else:
            paper_key = paper_id[0:ver_pos]    
        paper_url = arxiv_url + 'abs/' + paper_key
        
        # Try to find code link from GitHub search
        repo_url = get_code_link(paper_title)
        if repo_url is None:
            repo_url = get_code_link(paper_key)
        
        if repo_url is not None:
            content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|**[link]({})**|\n".format(
                   update_time,paper_title,paper_first_author,paper_key,paper_url,repo_url)
            content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({}), Code: **[{}]({})**".format(
                   update_time,paper_title,paper_first_author,paper_url,paper_url,repo_url,repo_url)
        else:
            content[paper_key] = "|**{}**|**{}**|{} et.al.|[{}]({})|null|\n".format(
                   update_time,paper_title,paper_first_author,paper_key,paper_url)
            content_to_web[paper_key] = "- {}, **{}**, {} et.al., Paper: [{}]({})".format(
                   update_time,paper_title,paper_first_author,paper_url,paper_url)

        # TODO: select useful comments
        comments = None
        if comments != None:
            content_to_web[paper_key] += f", {comments}\n"
        else:
            content_to_web[paper_key] += f"\n"

    data = {topic:content}
    data_web = {topic:content_to_web}
    return data,data_web 

def update_paper_links(filename):
    """Fill missing GitHub code links in an existing JSON paper database."""
    def parse_arxiv_string(value):
        parts = value.split("|")
        if len(parts) < 6:
            raise ValueError(f"Invalid paper row: {value!r}")
        date = parts[1].strip()
        title = parts[2].strip()
        authors = parts[3].strip()
        arxiv_id = re.sub(r'v\d+', '', parts[4].strip())
        code = parts[5].strip()
        return date, title, authors, arxiv_id, code

    json_data = load_json_file(filename)
    for keyword, papers in json_data.items():
        logging.info(f'keywords = {keyword}')
        for paper_id, contents in papers.items():
            try:
                update_time, paper_title, paper_first_author, paper_url, code_url = parse_arxiv_string(str(contents))
            except ValueError:
                logging.warning(f'Skipping malformed row {keyword}/{paper_id}')
                continue

            contents = "|{}|{}|{}|{}|{}|\n".format(
                update_time, paper_title, paper_first_author, paper_url, code_url)
            if '|null|' not in contents:
                json_data[keyword][paper_id] = contents
                continue

            repo_url = get_code_link(paper_title) or get_code_link(paper_id)
            if repo_url is not None:
                contents = contents.replace('|null|', f'|**[link]({repo_url})**|')
            json_data[keyword][paper_id] = contents

    with open(filename, "w") as f:
        json.dump(json_data, f, ensure_ascii=False)


def update_json_file(filename,data_dict):
    '''
    daily update json file using data_dict
    '''
    json_data = load_json_file(filename)
    
    # update papers in each keywords         
    for data in data_dict:
        for keyword in data.keys():
            papers = data[keyword]

            if keyword in json_data.keys():
                json_data[keyword].update(papers)
            else:
                json_data[keyword] = papers

    with open(filename,"w") as f:
        json.dump(json_data, f, ensure_ascii=False)
    
def json_to_md(filename,md_filename,
               task = '',
               to_web = False, 
               use_title = True, 
               use_tc = True,
               show_badge = True,
               use_b2t = True,
               source_repo_url = "https://github.com/GnafiY/MSSP-arxiv-daily",
               usage_path = "./docs/README.md",
               project_title = "MSSP Speech Paper Skim"):
    """
    @param filename: str
    @param md_filename: str
    @return None
    """
    def pretty_math(s:str) -> str:
        match = re.search(r"\$.*\$", s)
        if match is None:
            return s
        math_start, math_end = match.span()
        before, after = s[:math_start], s[math_end:]
        space_trail = " " if before and before[-1] not in " *" else ""
        space_leading = " " if after and after[0] not in " *" else ""
        return before + f'{space_trail}${match.group()[1:-1].strip()}${space_leading}' + after
  
    DateNow = datetime.date.today()
    DateNow = str(DateNow)
    DateNow = DateNow.replace('-','.')
    
    data = load_json_file(filename)

    # Clean the destination and recreate its parent directory if needed.
    md_parent = os.path.dirname(md_filename)
    if md_parent:
        os.makedirs(md_parent, exist_ok=True)
    with open(md_filename, "w") as f:
        pass

    # write data into README.md
    with open(md_filename,"a+") as f:

        if (use_title == True) and (to_web == True):
            f.write("---\n" + "layout: default\n" + "---\n\n")
        
        if show_badge == True:
            f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
            f.write(f"[![Forks][forks-shield]][forks-url]\n")
            f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
            f.write(f"[![Issues][issues-shield]][issues-url]\n\n")    
                
        if use_title == True:
            f.write(f"# {project_title}\n\n")
            f.write("## Updated on " + DateNow + "\n")
        else:
            f.write("> Updated on " + DateNow + "\n")

        # TODO: add usage
        f.write(f"> Usage instructions: [here]({usage_path})\n\n")
        f.write(f"> Generated automatically from arXiv. Source: [{source_repo_url}]({source_repo_url})\n\n")

        #Add: table of contents
        if use_tc == True:
            f.write("<details>\n")
            f.write("  <summary>Table of Contents</summary>\n")
            f.write("  <ol>\n")
            for keyword in data.keys():
                day_content = data[keyword]
                if not day_content:
                    continue
                kw = re.sub(r'[^a-z0-9 -]', '', keyword.lower()).replace(' ', '-')
                f.write(f"    <li><a href=#{kw}>{keyword}</a></li>\n")
            f.write("  </ol>\n")
            f.write("</details>\n\n")
        
        for keyword in data.keys():
            day_content = data[keyword]
            if not day_content:
                continue
            # the head of each part
            f.write(f"## {keyword}\n\n")

            if use_title == True :
                if to_web == False:
                    f.write("|Publish Date|Title|Authors|PDF|Code|\n" + "|---|---|---|---|---|\n")
                else:
                    f.write("| Publish Date | Title | Authors | PDF | Code |\n")
                    f.write("|:---------|:-----------------------|:---------|:------|:------|\n")

            # sort papers by date
            day_content = sort_papers(day_content)
        
            for _,v in day_content.items():
                if v is not None:
                    f.write(pretty_math(v)) # make latex pretty

            f.write(f"\n")
            
            #Add: back to top
            if use_b2t:
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")
            
        if show_badge == True:
            # we don't like long string, break it!
            f.write((f"[contributors-shield]: https://img.shields.io/github/"
                     f"contributors/GnafiY/MSSP-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[contributors-url]: https://github.com/GnafiY/"
                     f"MSSP-arxiv-daily/graphs/contributors\n"))
            f.write((f"[forks-shield]: https://img.shields.io/github/forks/GnafiY/"
                     f"MSSP-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[forks-url]: https://github.com/GnafiY/"
                     f"MSSP-arxiv-daily/network/members\n"))
            f.write((f"[stars-shield]: https://img.shields.io/github/stars/GnafiY/"
                     f"MSSP-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[stars-url]: https://github.com/GnafiY/"
                     f"MSSP-arxiv-daily/stargazers\n"))
            f.write((f"[issues-shield]: https://img.shields.io/github/issues/GnafiY/"
                     f"MSSP-arxiv-daily.svg?style=for-the-badge\n"))
            f.write((f"[issues-url]: https://github.com/GnafiY/"
                     f"MSSP-arxiv-daily/issues\n\n"))
                
    logging.info(f"{task} finished")        

def demo(**config):
    # TODO: use config
    data_collector = []
    data_collector_web= []
    
    keywords = config['kv']
    max_results = config['max_results']
    publish_readme = config['publish_readme']
    publish_gitpage = config['publish_gitpage']
    publish_wechat = config['publish_wechat']
    show_badge = config['show_badge']

    b_update = config['update_paper_links']
    logging.info(f'Update Paper Link = {b_update}')
    if config['update_paper_links'] == False:
        logging.info(f"GET daily papers begin")
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web = get_daily_papers(topic, query = keyword,
                                            max_results = max_results)
            data_collector.append(data)
            data_collector_web.append(data_web)
            print("\n")
        logging.info(f"GET daily papers end")

    # 1. update README.md file
    if publish_readme:
        json_file = config['json_readme_path']
        md_file   = config['md_readme_path']
        # update paper links
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:    
            # update json data
            update_json_file(json_file,data_collector)
        # json data to markdown
        json_to_md(json_file, md_file, task='Update Readme',
            show_badge=show_badge,
            source_repo_url=config.get('source_repo_url', 'https://github.com/GnafiY/MSSP-arxiv-daily'),
            usage_path='./docs/README.md',
            project_title=config.get('project_title', 'MSSP Speech Paper Skim'))

    # 2. update docs/index.md file (to gitpage)
    if publish_gitpage:
        json_file = config['json_gitpage_path']
        md_file   = config['md_gitpage_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:    
            update_json_file(json_file,data_collector)
        json_to_md(json_file, md_file, task='Update GitPage',
            to_web=True, show_badge=show_badge,
            use_tc=False, use_b2t=False,
            source_repo_url=config.get('source_repo_url', 'https://github.com/GnafiY/MSSP-arxiv-daily'),
            usage_path='./README.md',
            project_title=config.get('project_title', 'MSSP Speech Paper Skim'))

    # 3. Update docs/wechat.md file
    if publish_wechat:
        json_file = config['json_wechat_path']
        md_file   = config['md_wechat_path']
        # TODO: duplicated update paper links!!!
        if config['update_paper_links']:
            update_paper_links(json_file)
        else:    
            update_json_file(json_file, data_collector_web)
        json_to_md(json_file, md_file, task='Update Wechat',
            to_web=False, use_title=False, show_badge=show_badge,
            source_repo_url=config.get('source_repo_url', 'https://github.com/GnafiY/MSSP-arxiv-daily'),
            usage_path='./README.md',
            project_title=config.get('project_title', 'MSSP Speech Paper Skim'))

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--config_path',type=str, default='config.yaml',
                            help='configuration file path')
    parser.add_argument('--update_paper_links', default=False,
                        action="store_true",help='whether to update paper links etc.')                        
    args = parser.parse_args()
    config = load_config(args.config_path)
    config = {**config, 'update_paper_links':args.update_paper_links}
    demo(**config)
